export const skillsData = [
	{ img: "./img/skills/html5.svg", alt: "html5-image", title: "HTML5" },
	{ img: "./img/skills/css3.svg", alt: "css3-image", title: "CSS3" },
	{ img: "./img/skills/sass.svg", alt: "sass-image", title: "SASS/SCSS" },
	{
		img: "./img/skills/javascript.svg",
		alt: "javascript-image",
		title: "JavaScript",
	},
	{ img: "./img/skills/nodejs.svg", alt: "nodejs-image", title: "NodeJS" },
	{
		img: "./img/skills/firebase.svg",
		alt: "firebase-image",
		title: "Firebase",
	},
	{ img: "./img/skills/git.svg", alt: "git-image", title: "Git" },
	{ img: "./img/skills/github.svg", alt: "github-image", title: "GitHub" },
	{ img: "./img/skills/eslint.svg", alt: "eslint-image", title: "Eslint" },
	{
		img: "./img/skills/prettier.svg",
		alt: "prettier-image",
		title: "Prettier",
	},
	{
		img: "./img/skills/MUI.svg",
		alt: "materialui-image",
		title: "Material UI",
	},
	{
		img: "./img/skills/antdesign.svg",
		alt: "antdesign-image",
		title: "AntDesign",
	},
	{ img: "./img/skills/react.svg", alt: "react-image", title: "React" },
	{
		img: "./img/skills/typescript.svg",
		alt: "typescript-image",
		title: "Typescript",
	},
	{ img: "./img/skills/vitejs.svg", alt: "vite-image", title: "Vite" },
	{ img: "./img/skills/webpack.svg", alt: "webpack-image", title: "Webpack" },
	{ img: "./img/skills/codepen.svg", alt: "codepen-image", title: "Codepen" },
	{ img: "./img/skills/replit.svg", alt: "replit-image", title: "ReplIt" },
	{
		img: "./img/skills/PS.png",
		alt: "photoshop-image",
		title: "Adobe Photoshop",
	},
	{
		img: "./img/skills/Prepros.png",
		alt: "prepros-image",
		title: "Prepros",
	},
	{
		img: "./img/skills/vscode.png",
		alt: "vscode-image",
		title: "VS Code",
	},
	{
		img: "./img/skills/Figma.png",
		alt: "figma-image",
		title: "Figma",
	},
	{
		img: "./img/skills/pixso.jpg",
		alt: "pixso-image",
		title: "Pixso",
	},
	{
		img: "./img/skills/commercetools.svg",
		alt: "commercetools-image",
		title: "Commercetools",
	},
];

export const portfolioSitesData = [
	{
		link: "https://artemmikhalenia.github.io/FINAL_PROJECT/",
		img: "./img/Portfolio/websites/Azur Life.jpg",
		alt: "Azur Life",
		title: "Azur Life",
	},
	{
		link: "https://rolling-scopes-school.github.io/artemmikhalenia-JSFE2023Q4/coffee-house/",
		img: "./img/Portfolio/websites/CoffeeHouse.png",
		alt: "Coffee House",
		title: "Coffee House",
	},
	{
		link: "https://artemmikhalenia.github.io/Bicycle/",
		img: "./img/Portfolio/websites/Bicycle.jpg",
		alt: "Bicycle",
		title: "Bicycle",
	},
	{
		link: "https://artemmikhalenia.github.io/Site_Avalerian/",
		img: "./img/Portfolio/websites/Avalerian.png",
		alt: "Avalerian",
		title: "Avalerian",
	},
	{
		link: "https://artemmikhalenia.github.io/Site_BOOSTED/",
		img: "./img/Portfolio/websites/BOOSTED.jpg",
		alt: "BOOSTED",
		title: "BOOSTED",
	},
	{
		link: "https://artemmikhalenia.github.io/Site_Cupcakes/",
		img: "./img/Portfolio/websites/Cupcakes.jpg",
		alt: "Cupcakes",
		title: "Cupcakes",
	},
	{
		link: "https://artemmikhalenia.github.io/E-commerce_project3/",
		img: "./img/Portfolio/websites/Ecommerce.jpg",
		alt: "Ecommerce",
		title: "Ecommerce",
	},
	{
		link: "https://artemmikhalenia.github.io/Finsweet_project4/",
		img: "./img/Portfolio/websites/Finsweet.jpg",
		alt: "Finsweet",
		title: "Finsweet",
	},
	{
		link: "https://artemmikhalenia.github.io/Funhaus_project2/",
		img: "./img/Portfolio/websites/Funhaus.jpg",
		alt: "Funhaus",
		title: "Funhaus",
	},
	{
		link: "https://artemmikhalenia.github.io/Site_LOTR/",
		img: "./img/Portfolio/websites/LOTR.jpg",
		alt: "LOTR",
		title: "LOTR",
	},
	{
		link: "https://artemmikhalenia.github.io/Interno/",
		img: "./img/Portfolio/websites/Interno.jpg",
		alt: "Interno",
		title: "Interno",
	},
	{
		link: "https://artemmikhalenia.github.io/Aqua/",
		img: "./img/Portfolio/websites/Aqua.jpg",
		alt: "Aqua",
		title: "Aqua",
	},
	{
		link: "https://artemmikhalenia.github.io/Guitar/",
		img: "./img/Portfolio/websites/Guitar.jpg",
		alt: "Rhythm",
		title: "Rhythm",
	},
	{
		link: "https://artemmikhalenia.github.io/Site_Skillz/",
		img: "./img/Portfolio/websites/Skillz.jpg",
		alt: "Skillz",
		title: "Skillz",
	},
	{
		link: "https://artemmikhalenia.github.io/Binary/",
		img: "./img/Portfolio/websites/Binary.jpg",
		alt: "Binary",
		title: "Binary",
	},
	{
		link: "https://artemmikhalenia.github.io/Business-UI/",
		img: "./img/Portfolio/websites/Business.jpg",
		alt: "Business UI",
		title: "Business UI",
	},
	{
		link: "https://artemmikhalenia.github.io/PrimeOne/",
		img: "./img/Portfolio/websites/PrimeOne.jpg",
		alt: "PrimeOne",
		title: "PrimeOne",
	},
	{
		link: "https://artemmikhalenia.github.io/Travel/",
		img: "./img/Portfolio/websites/Travel.png",
		alt: "Travel",
		title: "Travel",
	},
	{
		link: "https://artemmikhalenia.github.io/Site_Rey_Negro/",
		img: "./img/Portfolio/websites/ReyNegro.png",
		alt: "ReyNegro",
		title: "ReyNegro",
	},
];
export const portfolioWebappsData = [
	{
		link: "https://artemmikhalenia.github.io/FINAL_PROJECT_JS_PERSONAL_TRAINER/",
		img: "./img/Portfolio/webapps/trainer.png",
		alt: "Personal Trainer",
		title: "Personal Trainer",
	},
	{
		link: "https://rolling-scopes-school.github.io/artemmikhalenia-JSFE2023Q4/nonograms/",
		img: "./img/Portfolio/webapps/nonograms.png",
		alt: "Nonograms",
		title: "Nonograms",
	},
	{
		link: "https://rolling-scopes-school.github.io/artemmikhalenia-JSFE2023Q4/rss-puzzle/",
		img: "./img/Portfolio/webapps/rss_puzzle.png",
		alt: "RSS Puzzle",
		title: "RSS Puzzle",
	},
	{
		link: "https://rolling-scopes-school.github.io/artemmikhalenia-JSFE2023Q4/hangman/",
		img: "./img/Portfolio/webapps/hangman.png",
		alt: "Hangman",
		title: "Hangman",
	},
];
export const portfolioWebappsReactData = [
	{
		link: "https://kept-town.netlify.app/",
		img: "./img/Portfolio/webappsreact/kepttown.png",
		alt: "Kepttown App",
		title: "Kepttown App",
	},
	{
		link: "https://weather-app5834.netlify.app/",
		img: "./img/Portfolio/webappsreact/weather_app.png",
		alt: "Weather App",
		title: "Weather App",
	},
	{
		link: "https://swoosh-store.netlify.app/",
		img: "./img/Portfolio/webappsreact/swoosh_store.png",
		alt: "Swoosh store",
		title: "Swoosh store",
	},
	{
		link: "https://memes-gen-app.netlify.app/",
		img: "./img/Portfolio/webappsreact/meme_generator.png",
		alt: "Meme generator",
		title: "Meme generator",
	},
	{
		link: "https://air-experience-react-clone.netlify.app/",
		img: "./img/Portfolio/webappsreact/airbnb_clone.png",
		alt: "AirBnb experiences clone",
		title: "AirBnb experiences clone",
	},
	{
		link: "https://digital-business-card-react-jsx.netlify.app/",
		img: "./img/Portfolio/webappsreact/digital_business_card.png",
		alt: "Digital business card",
		title: "Digital business card",
	},
];
